FROM mcr.microsoft.com/devcontainers/javascript-node:18-bullseye

WORKDIR /workspaces/dc-test-compose

#COPY ["package.json", "package-lock.json*", "./"]

#COPY . .

#RUN npm install



#EXPOSE $PORT
#RUN chown -R node /usr/src/app
#USER node
#ENTRYPOINT [ "npm", "run" ]
#ENTRYPOINT [ "npm", "run", "dev"]
